import type { Opportunity } from "./types";

/** Dados mockados para o MVP (substituídos depois por Server Actions + Supabase). */
export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 1,
    name: "Parafusadeira Bosch GSR 12V",
    marketplace: "Mercado Livre",
    imageUrl: "https://picsum.photos/seed/avisus-drill/720/480",
    price: 289.9,
    originalPrice: 459.9,
    freight: 12.5,
    freightFree: false,
    margin: 38,
    quality: "exceptional",
    category: "Ferramentas",
    region: "SC",
    city: "Palhoça",
    expiresLabel: "2h 15min",
    hot: true,
    buyUrl: "https://lista.mercadolivre.com.br/parafusadeira-bosch-gsr-12v",
    channelMargins: [
      { channel: "Mercado Livre", marketPrice: 459.9, fee: 0.15, netMargin: 38 },
      { channel: "Shopee", marketPrice: 449.0, fee: 0.18, netMargin: 31 },
      { channel: "Magazine Luiza", marketPrice: 452.0, fee: 0.16, netMargin: 34 },
    ],
    updatedAt: "2026-04-15T14:00:00.000Z",
  },
  {
    id: 2,
    name: "PlayStation 5 Slim Digital",
    marketplace: "Shopee",
    imageUrl: "https://picsum.photos/seed/avisus-ps5/720/480",
    price: 2799.0,
    originalPrice: 3699.0,
    freight: 0,
    freightFree: true,
    margin: 24,
    quality: "great",
    category: "Games",
    region: "SP",
    city: "São Paulo",
    expiresLabel: "5h 30min",
    hot: false,
    buyUrl: "https://shopee.com.br/",
    channelMargins: [
      { channel: "Mercado Livre", marketPrice: 3699.0, fee: 0.15, netMargin: 24 },
      { channel: "Shopee", marketPrice: 3650.0, fee: 0.18, netMargin: 19 },
      { channel: "Magazine Luiza", marketPrice: 3680.0, fee: 0.16, netMargin: 21 },
    ],
    updatedAt: "2026-04-16T09:30:00.000Z",
  },
  {
    id: 3,
    name: "Tênis Nike Air Max 90",
    marketplace: "Magazine Luiza",
    imageUrl: "https://picsum.photos/seed/avisus-nike/720/480",
    price: 449.9,
    originalPrice: 799.0,
    freight: 0,
    freightFree: true,
    margin: 42,
    quality: "exceptional",
    category: "Calçados",
    region: "RJ",
    city: "Rio de Janeiro",
    expiresLabel: "1d 4h",
    hot: true,
    buyUrl: "https://www.magazineluiza.com.br/",
    channelMargins: [
      { channel: "Mercado Livre", marketPrice: 789.0, fee: 0.15, netMargin: 39 },
      { channel: "Shopee", marketPrice: 799.0, fee: 0.18, netMargin: 35 },
      { channel: "Magazine Luiza", marketPrice: 779.0, fee: 0.16, netMargin: 42 },
    ],
    updatedAt: "2026-04-14T18:20:00.000Z",
  },
  {
    id: 4,
    name: "Fone Bluetooth Sony WH-CH720N",
    marketplace: "Mercado Livre",
    imageUrl: "https://picsum.photos/seed/avisus-headphone/720/480",
    price: 319.0,
    originalPrice: 499.0,
    freight: 9.9,
    freightFree: false,
    margin: 28,
    quality: "good",
    category: "Eletrônicos",
    region: "SP",
    city: "Campinas",
    expiresLabel: "45min",
    hot: false,
    buyUrl: "https://lista.mercadolivre.com.br/",
    channelMargins: [
      { channel: "Mercado Livre", marketPrice: 499.0, fee: 0.15, netMargin: 28 },
      { channel: "Shopee", marketPrice: 489.0, fee: 0.18, netMargin: 22 },
      { channel: "Magazine Luiza", marketPrice: 495.0, fee: 0.16, netMargin: 25 },
    ],
    updatedAt: "2026-04-16T11:05:00.000Z",
  },
  {
    id: 5,
    name: "Kit de ferramentas 89 peças",
    marketplace: "Shopee",
    imageUrl: "https://picsum.photos/seed/avisus-tools/720/480",
    price: 129.0,
    originalPrice: 219.0,
    freight: 15.0,
    freightFree: false,
    margin: 33,
    quality: "great",
    category: "Ferramentas",
    region: "PR",
    city: "Curitiba",
    expiresLabel: "8h",
    hot: false,
    buyUrl: "https://shopee.com.br/",
    channelMargins: [
      { channel: "Mercado Livre", marketPrice: 219.0, fee: 0.15, netMargin: 30 },
      { channel: "Shopee", marketPrice: 209.0, fee: 0.18, netMargin: 33 },
      { channel: "Magazine Luiza", marketPrice: 215.0, fee: 0.16, netMargin: 28 },
    ],
    updatedAt: "2026-04-13T08:00:00.000Z",
  },
];
